### ISSUE TITLE
CamTwist no longer compatible with Zoom 4.6.9

### ISSUE THREAD

**Issue by cleavenworth** [andrewodri/iphone-to-macos-camera#1]
Looks like one of the recent Zoom updates, 4.6.9, removes the entitlement that allows Zoom to load unvalidated libraries, preventing CamTwist from being recognized as a camera (the plugin is unsigned)

Using Zoom 4.6.8 I can still use CamTwist

https://objective-see.com/blog/blog_0x56.html

**Comment by andrewodri** [comment]
I'll do some testing on this tomorrow... Right now I'm running Zoom 4.6.9 and currently still have access to CamTwist. However, I a) haven't restarted too many services on my local system, and b) installed via Homebrew.

Thanks for the heads up, I'll update as things progress !

**Comment by andrewodri** [comment]
Hey @cleavenworth, so a couple of things: First, that was **very** interesting article. I knew Zoom was doing pretty stupid stuff (like [using AES ECB](https://citizenlab.ca/2020/04/move-fast-roll-your-own-crypto-a-quick-look-at-the-confidentiality-of-zoom-meetings/) for [audio](http://www.cs.jhu.edu/~cwright/oakland08.pdf) and [video](https://blog.filippo.io/the-ecb-penguin/) 🤦‍♂️), but that privilege escalation stuff (and for a user-space shell script at that!) is crazy, especially in a notarized production app!

Now in relation to the reported issues, here are a few thing's I've observed:

I had upgraded from 4.6.8 to 4.6.9, and Zoom's entitlements are the same... It still has both `com.apple.security.cs.disable-library-validation` and `com.apple.security.cs.disable-executable-page-protection` set to `true`. So this would lead me to think that, in typical Zoom style, that while fresh installs might allow HR & SIP to their jobs, upgrades only upgrade features and not security? I'm not too sure... My logs seem to indicate that while the latest delta was install on April 4th, the code signing certificate has a timestamp of "Apr 2, 2020 at 4:06:02 AM" which would [correspond with the release of 4.6.9](https://support.zoom.us/hc/en-us/articles/201361963-New-Updates-for-macOS), so either they lied, or they going out of their way to release separate new certificates where one is intentionally gimped.

When you run the following commands, what it the output?

* `mdls -name kMDItemVersion /Applications/zoom.us.app/ `
* `codesign -dvvv /Applications/zoom.us.app/`
* `codesign -d --entitlements :- /Applications/zoom.us.app/`

Also, it might be worth running `open ~/Library/Logs/zoominstall.log` to check out the install log and see if anything fishy is going on there... I'll dig through the logs and see if there is any more information on the deltas it sends through and where they come from...

-----

_Output from `mdls -name kMDItemVersion /Applications/zoom.us.app/`:_

```
kMDItemVersion = "4.6.9 (19273.0402)"
```

_Output from `codesign -dvvv /Applications/zoom.us.app/`:_

```
Executable=/Applications/zoom.us.app/Contents/MacOS/zoom.us
Identifier=us.zoom.xos
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20500 size=663 flags=0x10000(runtime) hashes=12+5 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha1=062fbb265084baa67599cf37e0021ab3f8f1afc3
CandidateCDHashFull sha1=062fbb265084baa67599cf37e0021ab3f8f1afc3
CandidateCDHash sha256=affd2c9acaa2fa0fda935bf38ee6acf1400a76ce
CandidateCDHashFull sha256=affd2c9acaa2fa0fda935bf38ee6acf1400a76ce21c7594886dea71e4022c958
Hash choices=sha1,sha256
CMSDigest=3fe5e9f30d5075baa19ba8e7a94a80d64b58bb49a2c65d1f68797923de3d7448
CMSDigestType=2
CDHash=affd2c9acaa2fa0fda935bf38ee6acf1400a76ce
Signature size=9080
Authority=Developer ID Application: Zoom Video Communications, Inc. (BJ4HAAB9B3)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Apr 2, 2020 at 4:06:02 AM
Info.plist entries=30
TeamIdentifier=BJ4HAAB9B3
Runtime Version=10.14.0
Sealed Resources version=2 rules=13 files=88
Internal requirements count=1 size=172
```

_Output from `codesign -d --entitlements :- /Applications/zoom.us.app/`:_

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.automation.apple-events</key>
	<true/>
	<key>com.apple.security.device.audio-input</key>
	<true/>
	<key>com.apple.security.device.camera</key>
	<true/>
	<key>com.apple.security.cs.disable-library-validation</key>
	<true/>
	<key>com.apple.security.cs.disable-executable-page-protection</key>
	<true/>
</dict>
</plist>
```

**Comment by andrewodri** [comment]
As of version 4.6.11 (20561.0413), entitlements are removed during the update process.

**Comment by andrewodri** [comment]
So this is issue if definitely confirmed... I'm try to see what other options might be our there to resolve/work around this.

In the meantime, for anyone needing to track down version 4.6.8, _at the time of writing_ it available here; so make sure you save a copy if you download it and think you may need it at some point in the future: https://us04web.zoom.us/client/4.6.19178.0323/Zoom.pkg

**Comment by andrewodri** [comment]
See this comment for a (rather poor) workaround... This requires an Apple Developer account, and while not ideal, it is a step in the right direction: https://github.com/johnboiles/obs-mac-virtualcam/issues/4#issuecomment-612168361

**Comment by hessius** [comment]
I just ran 

```
sudo codesign -f -s - /Applications/zoom.us.app
```

I don't know if that requires a dev account or not (I do have one), but was only prompted regular sudo pw and that option worked

**Comment by andrewodri** [comment]
Hey @hessius; I just confirmed this on a system without a developer comment... Thank you! I'll update the documentation with these comments 😄
